name: Testing
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go

      - name: Check out source code
        uses: actions/checkout@v3

      - name: up mysql docker 
        run: docker-compose up -d

      - name: Build
        run: go build .

      - name: Test
        run: go test -v .